# Generated by Django 5.2.17 on 2026-09-17 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0002_initial'),
        ('catalogo', '0002_initial'),
        ('perfiles', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('multimedia_id', models.BigAutoField(db_column='multimedia_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('ruta_archivo', models.CharField(db_column='ruta_archivo', max_length=500)),
                ('tamano_bytes', models.BigIntegerField(blank=True, db_column='tamano_bytes', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_column='fecha_subida')),
                ('anuncio', models.ForeignKey(blank=True, db_column='anuncio_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedias', to='anuncios.anuncio')),
                ('perfil', models.ForeignKey(blank=True, db_column='perfil_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='multimedias', to='perfiles.perfil')),
                ('tipo', models.ForeignKey(blank=True, db_column='tipo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='multimedias', to='catalogo.tipoarchivo')),
            ],
            options={
                'verbose_name': 'Multimedia',
                'verbose_name_plural': 'Multimedia',
                'db_table': 'multimedia',
                'ordering': ['-fecha_subida'],
                'managed': True,
            },
        ),
    ]
