# Generated by Django 5.2.17 on 2026-10-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='ruta_archivo',
        ),
        migrations.AddField(
            model_name='multimedia',
            name='archivo',
            field=models.FileField(blank=True, db_column='ruta_archivo', max_length=500, null=True, upload_to='multimedia/%Y/%m/'),
        ),
    ]
