# Generated by Django 5.2.17 on 2026-10-02 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multimedia', '0002_remove_multimedia_ruta_archivo_multimedia_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multimedia',
            name='anuncio',
        ),
    ]
