# Generated by Django 5.2.17 on 2026-09-17 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('anuncio_id', models.BigAutoField(db_column='anuncio_id', primary_key=True, serialize=False)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, db_column='fecha_publicacion')),
                ('titulo', models.CharField(db_column='titulo', max_length=160)),
                ('contenido', models.CharField(db_column='contenido', max_length=750)),
            ],
            options={
                'verbose_name': 'Anuncio',
                'verbose_name_plural': 'Anuncios',
                'db_table': 'anuncio',
                'ordering': ['-fecha_publicacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('comentario_id', models.BigAutoField(db_column='comentario_id', primary_key=True, serialize=False)),
                ('contenido', models.CharField(db_column='contenido', max_length=500)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, db_column='fecha_publicacion')),
                ('esta_eliminado', models.BooleanField(db_column='esta_eliminado', default=False)),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'db_table': 'comentario',
                'ordering': ['-fecha_publicacion'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoAnuncio',
            fields=[
                ('tipo_anuncio_id', models.BigAutoField(db_column='tipo_anuncio_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de anuncio',
                'verbose_name_plural': 'Tipos de anuncio',
                'db_table': 'tipo_anuncio',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
    ]
