# Generated by Django 5.2.17 on 2026-09-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anuncios', '0001_initial'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anuncio',
            name='perfil',
            field=models.ForeignKey(blank=True, db_column='perfil_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='anuncios', to='perfiles.perfil'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='anuncio',
            field=models.ForeignKey(blank=True, db_column='anuncio_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='anuncios.anuncio'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='perfil',
            field=models.ForeignKey(blank=True, db_column='perfil_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to='perfiles.perfil'),
        ),
        migrations.AddField(
            model_name='anuncio',
            name='tipo_anuncio',
            field=models.ForeignKey(blank=True, db_column='tipo_anuncio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuncios', to='anuncios.tipoanuncio'),
        ),
    ]
