# Generated by Django 5.2.17 on 2026-10-03 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0002_initial'),
        ('multimedia', '0003_remove_multimedia_anuncio'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnuncioMultimedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField(db_column='orden', default=0)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, db_column='fecha_agregado')),
                ('anuncio', models.ForeignKey(db_column='anuncio_id', on_delete=django.db.models.deletion.CASCADE, related_name='anuncio_multimedias', to='anuncios.anuncio')),
                ('multimedia', models.ForeignKey(db_column='multimedia_id', on_delete=django.db.models.deletion.CASCADE, related_name='anuncio_multimedias', to='multimedia.multimedia')),
            ],
            options={
                'verbose_name': 'Anuncio-Multimedia',
                'verbose_name_plural': 'Anuncios-Multimedia',
                'db_table': 'anuncio_multimedia',
                'ordering': ['orden', 'fecha_agregado'],
                'managed': True,
                'unique_together': {('anuncio', 'multimedia')},
            },
        ),
    ]
