# Generated by Django 5.2.17 on 2026-09-30 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('chat_id', models.BigAutoField(db_column='chat_id', primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chats',
                'db_table': 'chat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MensajeLeido',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('leido_en', models.DateTimeField(auto_now_add=True, db_column='leido_en')),
            ],
            options={
                'verbose_name': 'Mensaje leído',
                'verbose_name_plural': 'Mensajes leídos',
                'db_table': 'mensaje_leido',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('mensaje_id', models.BigAutoField(db_column='mensaje_id', primary_key=True, serialize=False)),
                ('contenido', models.CharField(db_column='contenido', max_length=500)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_column='fecha_envio')),
                ('esta_eliminado', models.BooleanField(db_column='esta_eliminado', default=False)),
                ('chat', models.ForeignKey(blank=True, db_column='chat_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='chats.chat')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'mensaje',
                'ordering': ['fecha_envio'],
                'managed': True,
            },
        ),
    ]
