# Generated by Django 5.2.17 on 2026-09-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='perfil',
            field=models.ForeignKey(blank=True, db_column='perfil_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='perfiles.perfil'),
        ),
        migrations.AddField(
            model_name='mensajeleido',
            name='perfil',
            field=models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, to='perfiles.perfil'),
        ),
        migrations.AlterUniqueTogether(
            name='mensajeleido',
            unique_together={('mensaje', 'perfil')},
        ),
    ]
