# Generated by Django 5.2.17 on 2026-10-03 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeAdjunto',
            fields=[
                ('adjunto_id', models.BigAutoField(db_column='adjunto_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=255)),
                ('archivo', models.FileField(db_column='ruta_archivo', max_length=500, upload_to='chat/%Y/%m/')),
                ('tamano_bytes', models.BigIntegerField(blank=True, db_column='tamano_bytes', null=True)),
                ('content_type', models.CharField(blank=True, db_column='content_type', max_length=100, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_column='fecha_subida')),
                ('mensaje', models.ForeignKey(db_column='mensaje_id', on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='chats.mensaje')),
            ],
            options={
                'verbose_name': 'Adjunto de mensaje',
                'verbose_name_plural': 'Adjuntos de mensajes',
                'db_table': 'mensaje_adjunto',
                'ordering': ['fecha_subida'],
                'managed': True,
            },
        ),
    ]
