# Generated by Django 5.2.17 on 2026-10-03 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_mensajeadjunto'),
        ('perfiles', '0003_alter_perfil_correo_alter_perfil_edad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajeadjunto',
            name='perfil',
            field=models.ForeignKey(blank=True, db_column='perfil_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos_subidos', to='perfiles.perfil'),
        ),
        migrations.AlterField(
            model_name='mensajeadjunto',
            name='mensaje',
            field=models.ForeignKey(blank=True, db_column='mensaje_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='chats.mensaje'),
        ),
    ]
