# Generated by Django 5.2.17 on 2026-09-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comarca',
            fields=[
                ('comarca_id', models.BigAutoField(db_column='comarca_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Comarca',
                'verbose_name_plural': 'Comarcas',
                'db_table': 'comarca',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GeneroMusical',
            fields=[
                ('genero_musical_id', models.BigAutoField(db_column='genero_musical_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
            ],
            options={
                'verbose_name': 'Género musical',
                'verbose_name_plural': 'Géneros musicales',
                'db_table': 'genero_musical',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('grupo_id', models.BigAutoField(db_column='grupo_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupo',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('instrumento_id', models.BigAutoField(db_column='instrumento_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=25)),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
                'db_table': 'instrumento',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoArchivo',
            fields=[
                ('tipo_archivo_id', models.BigAutoField(db_column='tipo_archivo_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=10)),
                ('extension', models.CharField(db_column='extension', max_length=10)),
                ('mime_type', models.CharField(db_column='mime_type', max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de archivo',
                'verbose_name_plural': 'Tipos de archivo',
                'db_table': 'tipo_archivo',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciudad_id', models.BigAutoField(db_column='ciudad_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=75)),
                ('comarca', models.ForeignKey(blank=True, db_column='comarca_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ciudades', to='catalogo.comarca')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
                'ordering': ['nombre'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GrupoGenero',
            fields=[
                ('grupo', models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='catalogo.grupo')),
            ],
            options={
                'verbose_name': 'Grupo-Género',
                'verbose_name_plural': 'Grupos-Géneros',
                'db_table': 'grupo_genero',
                'managed': True,
            },
        ),
    ]
