# Generated by Django 5.2.17 on 2026-09-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='creador_perfil',
            field=models.ForeignKey(blank=True, db_column='creador_perfil_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_creados', to='perfiles.perfil'),
        ),
        migrations.AddField(
            model_name='grupogenero',
            name='genero',
            field=models.ForeignKey(db_column='genero_id', on_delete=django.db.models.deletion.CASCADE, to='catalogo.generomusical'),
        ),
        migrations.AlterUniqueTogether(
            name='grupogenero',
            unique_together={('grupo', 'genero')},
        ),
    ]
