# Generated by Django 5.2.17 on 2026-09-17 21:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuario_id', models.BigAutoField(db_column='usuario_id', primary_key=True, serialize=False)),
                ('nickname', models.CharField(db_column='nickname', max_length=50, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
                ('creado_en', models.DateTimeField(db_column='creado_en', default=django.utils.timezone.now)),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('is_superuser', models.BooleanField(db_column='is_superuser', default=False)),
                ('is_active', models.BooleanField(db_column='is_active', default=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuario',
                'managed': True,
            },
        ),
    ]
