# Generated by Django 5.2.17 on 2026-09-17 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('perfil_id', models.BigAutoField(db_column='perfil_id', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=50)),
                ('apellido', models.CharField(db_column='apellido', max_length=50)),
                ('correo', models.CharField(db_column='correo', max_length=100, unique=True)),
                ('numero_telefono', models.BigIntegerField(blank=True, db_column='numero_telefono', null=True, unique=True)),
                ('edad', models.IntegerField(blank=True, db_column='edad', null=True)),
                ('sexo', models.CharField(blank=True, db_column='sexo', max_length=18, null=True)),
                ('disponibilidad', models.BooleanField(db_column='disponibilidad', default=True)),
                ('descripcion', models.CharField(db_column='descripcion', max_length=300)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('fecha_baja', models.DateTimeField(blank=True, db_column='fecha_baja', null=True)),
                ('comarca', models.ForeignKey(blank=True, db_column='comarca_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='perfiles', to='catalogo.comarca')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'db_table': 'perfil',
                'ordering': ['perfil_id'],
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilChat',
            fields=[
                ('perfil', models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='perfiles.perfil')),
                ('fecha_union', models.DateTimeField(auto_now_add=True, db_column='fecha_union')),
            ],
            options={
                'verbose_name': 'Perfil-Chat',
                'verbose_name_plural': 'Perfiles-Chats',
                'db_table': 'perfil_chat',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilGeneroMusical',
            fields=[
                ('perfil', models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='perfiles.perfil')),
            ],
            options={
                'verbose_name': 'Perfil-Género musical',
                'verbose_name_plural': 'Perfiles-Géneros musicales',
                'db_table': 'perfil_genero_musical',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilGrupo',
            fields=[
                ('perfil', models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='perfiles.perfil')),
            ],
            options={
                'verbose_name': 'Perfil-Grupo',
                'verbose_name_plural': 'Perfiles-Grupos',
                'db_table': 'perfil_grupo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PerfilInstrumento',
            fields=[
                ('perfil', models.ForeignKey(db_column='perfil_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='perfiles.perfil')),
            ],
            options={
                'verbose_name': 'Perfil-Instrumento',
                'verbose_name_plural': 'Perfiles-Instrumentos',
                'db_table': 'perfil_instrumento',
                'managed': True,
            },
        ),
    ]
