# Generated by Django 5.2.17 on 2026-09-30 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_initial'),
        ('perfiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='tipo',
            field=models.CharField(choices=[('usuario', 'Usuario'), ('grupo', 'Grupo'), ('local', 'Local')], db_column='tipo', default='usuario', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='perfil',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'usuario')), fields=('usuario',), name='unique_perfil_personal_por_usuario'),
        ),
    ]
