# Generated by Django 5.2.17 on 2026-09-17 21:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_initial'),
        ('chats', '0002_initial'),
        ('perfiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.ForeignKey(blank=True, db_column='usuario_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='perfilchat',
            name='chat',
            field=models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, to='chats.chat'),
        ),
        migrations.AddField(
            model_name='perfilgeneromusical',
            name='genero',
            field=models.ForeignKey(db_column='genero_id', on_delete=django.db.models.deletion.CASCADE, to='catalogo.generomusical'),
        ),
        migrations.AddField(
            model_name='perfilgrupo',
            name='grupo',
            field=models.ForeignKey(db_column='grupo_id', on_delete=django.db.models.deletion.CASCADE, to='catalogo.grupo'),
        ),
        migrations.AddField(
            model_name='perfilinstrumento',
            name='instrumento',
            field=models.ForeignKey(db_column='instrumento_id', on_delete=django.db.models.deletion.CASCADE, to='catalogo.instrumento'),
        ),
        migrations.AlterUniqueTogether(
            name='perfilchat',
            unique_together={('perfil', 'chat')},
        ),
        migrations.AlterUniqueTogether(
            name='perfilgeneromusical',
            unique_together={('perfil', 'genero')},
        ),
        migrations.AlterUniqueTogether(
            name='perfilgrupo',
            unique_together={('perfil', 'grupo')},
        ),
        migrations.AlterUniqueTogether(
            name='perfilinstrumento',
            unique_together={('perfil', 'instrumento')},
        ),
    ]
