# Generated by Django 5.2.17 on 2026-10-01 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfiles', '0002_perfil_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='correo',
            field=models.EmailField(db_column='correo', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='edad',
            field=models.IntegerField(blank=True, db_column='edad', null=True, validators=[django.core.validators.MinValueValidator(16, message='La edad mínima es 16 años'), django.core.validators.MaxValueValidator(100, message='La edad máxima es 100 años')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='numero_telefono',
            field=models.CharField(blank=True, db_column='numero_telefono', max_length=20, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos, opcionalmente con prefijo +', regex='^\\+?[0-9]{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro'), ('Prefiero no decir', 'Prefiero no decir')], db_column='sexo', max_length=18, null=True),
        ),
    ]
